/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthGoalsRouteRouteImport } from './routes/_auth.goals.route'
import { Route as GuestLoginRouteImport } from './routes/_guest.login'
import { Route as GuestSignupRouteImport } from './routes/_guest.signup'
import { Route as AuthGoalsIndexRouteImport } from './routes/_auth.goals.index'
import { Route as AuthGoalsGoalIDRouteRouteImport } from './routes/_auth.goals.$goalID.route'
import { Route as AuthGoalsNewRouteImport } from './routes/_auth.goals.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthGoalsGoalIDIndexRouteImport } from './routes/_auth.goals.$goalID.index'
import { Route as AuthGoalsGoalIDEditRouteImport } from './routes/_auth.goals.$goalID.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoalsRouteRoute = AuthGoalsRouteRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRoute,
} as any)
const AuthGoalsIndexRoute = AuthGoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGoalsRouteRoute,
} as any)
const AuthGoalsGoalIDRouteRoute = AuthGoalsGoalIDRouteRouteImport.update({
  id: '/$goalID',
  path: '/$goalID',
  getParentRoute: () => AuthGoalsRouteRoute,
} as any)
const AuthGoalsNewRoute = AuthGoalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthGoalsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoalsGoalIDIndexRoute = AuthGoalsGoalIDIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGoalsGoalIDRouteRoute,
} as any)
const AuthGoalsGoalIDEditRoute = AuthGoalsGoalIDEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthGoalsGoalIDRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goals': typeof AuthGoalsRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/goals/$goalID': typeof AuthGoalsGoalIDRouteRouteWithChildren
  '/goals/new': typeof AuthGoalsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/goals/': typeof AuthGoalsIndexRoute
  '/goals/$goalID/edit': typeof AuthGoalsGoalIDEditRoute
  '/goals/$goalID/': typeof AuthGoalsGoalIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/goals/new': typeof AuthGoalsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/goals': typeof AuthGoalsIndexRoute
  '/goals/$goalID/edit': typeof AuthGoalsGoalIDEditRoute
  '/goals/$goalID': typeof AuthGoalsGoalIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/goals': typeof AuthGoalsRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/goals/$goalID': typeof AuthGoalsGoalIDRouteRouteWithChildren
  '/_auth/goals/new': typeof AuthGoalsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/goals/': typeof AuthGoalsIndexRoute
  '/_auth/goals/$goalID/edit': typeof AuthGoalsGoalIDEditRoute
  '/_auth/goals/$goalID/': typeof AuthGoalsGoalIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goals'
    | '/login'
    | '/signup'
    | '/goals/$goalID'
    | '/goals/new'
    | '/api/auth/$'
    | '/goals/'
    | '/goals/$goalID/edit'
    | '/goals/$goalID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/goals/new'
    | '/api/auth/$'
    | '/goals'
    | '/goals/$goalID/edit'
    | '/goals/$goalID'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/goals'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/goals/$goalID'
    | '/_auth/goals/new'
    | '/api/auth/$'
    | '/_auth/goals/'
    | '/_auth/goals/$goalID/edit'
    | '/_auth/goals/$goalID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/goals': {
      id: '/_auth/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthGoalsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/goals/': {
      id: '/_auth/goals/'
      path: '/'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthGoalsIndexRouteImport
      parentRoute: typeof AuthGoalsRouteRoute
    }
    '/_auth/goals/$goalID': {
      id: '/_auth/goals/$goalID'
      path: '/$goalID'
      fullPath: '/goals/$goalID'
      preLoaderRoute: typeof AuthGoalsGoalIDRouteRouteImport
      parentRoute: typeof AuthGoalsRouteRoute
    }
    '/_auth/goals/new': {
      id: '/_auth/goals/new'
      path: '/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof AuthGoalsNewRouteImport
      parentRoute: typeof AuthGoalsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/goals/$goalID/': {
      id: '/_auth/goals/$goalID/'
      path: '/'
      fullPath: '/goals/$goalID/'
      preLoaderRoute: typeof AuthGoalsGoalIDIndexRouteImport
      parentRoute: typeof AuthGoalsGoalIDRouteRoute
    }
    '/_auth/goals/$goalID/edit': {
      id: '/_auth/goals/$goalID/edit'
      path: '/edit'
      fullPath: '/goals/$goalID/edit'
      preLoaderRoute: typeof AuthGoalsGoalIDEditRouteImport
      parentRoute: typeof AuthGoalsGoalIDRouteRoute
    }
  }
}

interface AuthGoalsGoalIDRouteRouteChildren {
  AuthGoalsGoalIDEditRoute: typeof AuthGoalsGoalIDEditRoute
  AuthGoalsGoalIDIndexRoute: typeof AuthGoalsGoalIDIndexRoute
}

const AuthGoalsGoalIDRouteRouteChildren: AuthGoalsGoalIDRouteRouteChildren = {
  AuthGoalsGoalIDEditRoute: AuthGoalsGoalIDEditRoute,
  AuthGoalsGoalIDIndexRoute: AuthGoalsGoalIDIndexRoute,
}

const AuthGoalsGoalIDRouteRouteWithChildren =
  AuthGoalsGoalIDRouteRoute._addFileChildren(AuthGoalsGoalIDRouteRouteChildren)

interface AuthGoalsRouteRouteChildren {
  AuthGoalsGoalIDRouteRoute: typeof AuthGoalsGoalIDRouteRouteWithChildren
  AuthGoalsNewRoute: typeof AuthGoalsNewRoute
  AuthGoalsIndexRoute: typeof AuthGoalsIndexRoute
}

const AuthGoalsRouteRouteChildren: AuthGoalsRouteRouteChildren = {
  AuthGoalsGoalIDRouteRoute: AuthGoalsGoalIDRouteRouteWithChildren,
  AuthGoalsNewRoute: AuthGoalsNewRoute,
  AuthGoalsIndexRoute: AuthGoalsIndexRoute,
}

const AuthGoalsRouteRouteWithChildren = AuthGoalsRouteRoute._addFileChildren(
  AuthGoalsRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthGoalsRouteRoute: typeof AuthGoalsRouteRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGoalsRouteRoute: AuthGoalsRouteRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
