/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as EditGoalIDRouteImport } from './routes/edit.$goalID'
import { Route as OverviewGoalIDRouteImport } from './routes/overview.$goalID'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const EditGoalIDRoute = EditGoalIDRouteImport.update({
  id: '/edit/$goalID',
  path: '/edit/$goalID',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewGoalIDRoute = OverviewGoalIDRouteImport.update({
  id: '/overview/$goalID',
  path: '/overview/$goalID',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit/$goalID': typeof EditGoalIDRoute
  '/overview/$goalID': typeof OverviewGoalIDRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit/$goalID': typeof EditGoalIDRoute
  '/overview/$goalID': typeof OverviewGoalIDRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit/$goalID': typeof EditGoalIDRoute
  '/overview/$goalID': typeof OverviewGoalIDRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/sign-in'
    | '/sign-up'
    | '/edit/$goalID'
    | '/overview/$goalID'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/sign-in'
    | '/sign-up'
    | '/edit/$goalID'
    | '/overview/$goalID'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/sign-in'
    | '/sign-up'
    | '/edit/$goalID'
    | '/overview/$goalID'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  EditGoalIDRoute: typeof EditGoalIDRoute
  OverviewGoalIDRoute: typeof OverviewGoalIDRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$goalID': {
      id: '/edit/$goalID'
      path: '/edit/$goalID'
      fullPath: '/edit/$goalID'
      preLoaderRoute: typeof EditGoalIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/$goalID': {
      id: '/overview/$goalID'
      path: '/overview/$goalID'
      fullPath: '/overview/$goalID'
      preLoaderRoute: typeof OverviewGoalIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  EditGoalIDRoute: EditGoalIDRoute,
  OverviewGoalIDRoute: OverviewGoalIDRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
